apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: java-dump-pvc
  namespace: 0913market
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 3Gi